const QUE_DATA = [
  {
    id: 1,
    name: "Quẻ Số 1 - Thượng Thượng (Đại Cát)",
    name_en: "Stick #1 - Supreme Fortune (Most Auspicious)",
    title: "Khai Hoa Kết Quả",
    title_en: "Blooming Flowers & Bearing Fruits",
    poem: "Khai hoa kết quả tự nhiên thành\nY bối huỳnh kim bộ ngọc đình\nĐông tây nam bắc giai thông đạt\nVạn sự hanh thông đắc thái bình.",
    poem_en: "Khai hoa kết quả tự nhiên thành\nY bối huỳnh kim bộ ngọc đình\nĐông tây nam bắc giai thông đạt\nVạn sự hanh thông đắc thái bình.",
    translation: "Hoa nở kết quả tự nhiên thành,\nÁo mặc vàng ròng, bước điện ngọc.\nĐông tây nam bắc đều thông đạt,\nVạn sự hanh thông đắc thái bình.",
    translation_en: "Flowers bloom and fruits bear naturally,\nDressed in gold, walking through jade halls.\nEast, west, south, north — all paths lead to success,\nAll matters prosper, peace and harmony prevail.",
    meaning: "Mọi sự cát tường, cầu tài đắc tài, cầu danh đắc danh, gia đạo bình an vô sự. Thời cơ chín muồi, hành sự như ý.",
    meaning_en: "All is auspicious. Seek wealth and you shall find it, seek fame and you shall earn it. Family harmony and peace prevail. The time is ripe, all endeavors shall succeed.",
    details: {
      "Bản thân": "Bản mệnh vững vàng, vận thế cực thịnh, có quý nhân phù trợ từ nhiều phương.",
      "Gia trạch": "Gia môn hưng vượng, gia đình hòa thuận, có tin vui về người hoặc thêm của.",
      "Mưu sự": "Mọi việc dự định đều thành công dễ dàng, không gặp trở ngại.",
      "Cầu tài": "Tài lộc dồi dào, kinh doanh đắc lợi, đầu tư sinh lời lớn.",
      "Tật bệnh": "Sức khỏe dồi dào, nếu đang có bệnh sẽ nhanh chóng bình phục.",
      "Hôn nhân": "Lương duyên tiền định, gia đạo hạnh phúc viên mãn.",
      "Xuất hành": "Đi xa thuận lợi, có bạn hiền giúp đỡ, hướng đông nam cát tường."
    },
    details_en: {
      "Personal": "Destiny is strong and stable, fortune at its peak, with noble benefactors from all directions.",
      "Home & Family": "Family prosperity rising, household harmonious, joyful news of people or added wealth.",
      "Plans & Career": "All planned endeavors succeed easily without obstacles.",
      "Wealth": "Abundant wealth and fortune. Business profits greatly, investments yield large returns.",
      "Health": "Excellent health. If currently ill, swift recovery ahead.",
      "Marriage": "A destined good match. Family life perfectly blissful.",
      "Travel": "Travel is very favorable with helpful companions. Southeast direction most auspicious."
    }
  },
  {
    id: 2,
    name: "Quẻ Số 2 - Thượng Cát",
    name_en: "Stick #2 - Great Fortune",
    title: "Xuân Hoa Thu Cúc",
    title_en: "Spring Blossoms & Autumn Chrysanthemums",
    poem: "Thu cúc xuân hoa mỗi tự vinh\nThời lai vận chuyển cát nhân tinh\nKim ngân tài bảo trùng trùng chí\nĐộc bộ phong vân lập đại danh.",
    poem_en: "Thu cúc xuân hoa mỗi tự vinh\nThời lai vận chuyển cát nhân tinh\nKim ngân tài bảo trùng trùng chí\nĐộc bộ phong vân lập đại danh.",
    translation: "Cúc thu hoa xuân mỗi thứ tự tươi tốt,\nThời tới vận chuyển nhờ sao lành chiếu mệnh.\nVàng bạc tài bảo trùng trùng đưa tới,\nMột mình bước lên gió mây lập công danh lớn.",
    translation_en: "Autumn mums and spring flowers each flourish in their season,\nWhen fortune's time arrives, lucky stars illuminate your path.\nGold, silver, and treasures come in endless waves,\nAlone you stride through wind and clouds to establish great fame.",
    meaning: "Mọi sự thuận lợi, thời vận hanh thông, công danh rạng rỡ. Vạn sự khởi đầu tuy chậm nhưng kết quả mỹ mãn.",
    meaning_en: "All is favorable, fortune flows smoothly, career shines brightly. Beginnings may be slow but results will be splendid.",
    details: {
      "Bản thân": "Bản thân an vui, tinh thần phấn chấn, gặp nhiều may mắn bất ngờ.",
      "Gia trạch": "Gia đạo yên vui, trong nhà có hỷ sự, con cháu hiếu thảo học hành đỗ đạt.",
      "Mưu sự": "Gặp thời vận tốt, mưu sự ắt thành nhưng cần kiên nhẫn đợi đúng thời cơ.",
      "Cầu tài": "Tài lộc hanh thông, mua bán có duyên, tiền bạc dư dả.",
      "Tật bệnh": "Không có bệnh tật gì lớn, cơ thể tráng kiện.",
      "Hôn nhân": "Duyên lành tự đến, vợ chồng hòa hợp, trăm năm hạnh phúc.",
      "Xuất hành": "Xuất hành hướng Nam hoặc Đông rất có lợi cho danh tiếng và tiền tài."
    },
    details_en: {
      "Personal": "Peace and joy abound, spirits are high, unexpected good fortune awaits.",
      "Home & Family": "Household joyful, celebrations at home, children filial and excel in studies.",
      "Plans & Career": "Good timing ahead. Plans will succeed but patience is needed for the right moment.",
      "Wealth": "Wealth flows smoothly, trade is favorable, money in abundance.",
      "Health": "No major illness, body is strong and vigorous.",
      "Marriage": "Good match arrives naturally, couple harmonious, a lifetime of happiness.",
      "Travel": "Traveling south or east is very beneficial for reputation and wealth."
    }
  },
  {
    id: 3,
    name: "Quẻ Số 3 - Trung Bình",
    name_en: "Stick #3 - Average Fortune",
    title: "Thuận Thủy Hành Chu",
    title_en: "Sailing with the Current",
    poem: "Phong điềm lãng tịnh khả phi thuyền\nVạn lý ba đào nhậm tự nhiên\nTĩnh thủ gia môn vô sự động\nTùy cơ ứng biến cát vô biên.",
    poem_en: "Phong điềm lãng tịnh khả phi thuyền\nVạn lý ba đào nhậm tự nhiên\nTĩnh thủ gia môn vô sự động\nTùy cơ ứng biến cát vô biên.",
    translation: "Gió lặng sóng êm có thể thả thuyền,\nVạn dặm sóng gió cứ để tự nhiên.\nYên lặng giữ gia môn, chớ động đậy,\nTùy cơ ứng biến tốt lành khôn cùng.",
    translation_en: "When winds are calm and waves are still, set sail freely,\nThrough ten thousand miles of storms, let nature take its course.\nQuietly guard your home, make no rash moves,\nAdapt to circumstances and blessings shall be boundless.",
    meaning: "Bình thường ổn định, không nên thay đổi lớn hay đầu tư mạo hiểm. Giữ nguyên trạng cũ sẽ an toàn và cát lành.",
    meaning_en: "Stable and steady. Avoid major changes or risky investments. Maintaining the status quo ensures safety and good fortune.",
    details: {
      "Bản thân": "Tâm tính bình hòa, không nên tham lam hay nóng vội mà hỏng việc.",
      "Gia trạch": "Gia đạo bình an, cuộc sống ổn định, tránh tranh chấp cãi cọ.",
      "Mưu sự": "Mưu sự trung bình, không nên mở rộng quy mô lớn, làm việc cũ thì tốt.",
      "Cầu tài": "Tài lộc vừa đủ dùng, không có tài lộc lớn nhưng cũng không lo thiếu thốn.",
      "Tật bệnh": "Bệnh nhẹ sớm khỏi, nên chú ý nghỉ ngơi và ăn uống điều độ.",
      "Hôn nhân": "Tình duyên bình thường, cần bao dung thấu hiểu nhau hơn.",
      "Xuất hành": "Chỉ nên đi xa khi thật sự cần thiết, đi gần thì an toàn hơn."
    },
    details_en: {
      "Personal": "Keep a calm temperament. Avoid greed or impatience that could ruin matters.",
      "Home & Family": "Household peaceful, life stable. Avoid disputes and arguments.",
      "Plans & Career": "Average prospects. Don't expand too aggressively; continuing current work is best.",
      "Wealth": "Wealth is sufficient, no great fortune but no want either.",
      "Health": "Minor ailments heal quickly. Rest well and eat moderately.",
      "Marriage": "Romance is ordinary. More tolerance and understanding between partners is needed.",
      "Travel": "Travel only when truly necessary. Short trips are safer than long journeys."
    }
  },
  {
    id: 4,
    name: "Quẻ Số 4 - Hạ Hạ",
    name_en: "Stick #4 - Misfortune",
    title: "Vũ Bạt Phong Cuồng",
    title_en: "Violent Storms & Raging Winds",
    poem: "Phong cuồng vũ bạo vũ khuynh sào\nBộ bộ kinh tâm lộ cách đào\nTẩu bích phi sa đa trướng ngại\nTạm nghi thủ cựu lánh ba đào.",
    poem_en: "Phong cuồng vũ bạo vũ khuynh sào\nBộ bộ kinh tâm lộ cách đào\nTẩu bích phi sa đa trướng ngại\nTạm nghi thủ cựu lánh ba đào.",
    translation: "Gió cuồng mưa dữ làm đổ tổ chim,\nMỗi bước giật mình đường đi đầy sóng lớn.\nĐá bay cát chạy nhiều chướng ngại,\nTạm nên giữ cũ để lánh sóng gió.",
    translation_en: "Raging winds and violent rains topple the bird's nest,\nEvery step startles the heart on a path fraught with peril.\nFlying rocks and blowing sand — obstacles abound,\nBest to hold steady and shelter from the storm.",
    meaning: "Vận thế gặp nhiều trắc trở, gian nan, dễ gặp thị phi hoặc tổn thất. Cần ẩn nhẫn, không tiến hành việc lớn.",
    meaning_en: "Fortune is beset by many obstacles and hardships, prone to disputes or losses. Exercise patience and refrain from major undertakings.",
    details: {
      "Bản thân": "Bản mệnh yếu, đề phòng tiểu nhân hãm hại, thị phi vây quanh.",
      "Gia trạch": "Trong nhà bất hòa, đề phòng trộm cắp, mất mát của cải.",
      "Mưu sự": "Khó thành công, dự án dễ bị đình trệ hoặc đổ vỡ, nên hoãn lại.",
      "Cầu tài": "Tài lộc suy kiệt, dễ hao tài tốn của, tuyệt đối tránh cho vay mượn.",
      "Tật bệnh": "Chú ý bệnh nặng, phòng ngừa tai nạn bất ngờ, nên tích cực đi khám.",
      "Hôn nhân": "Nhiều trắc trở, xung đột gay gắt, dễ dẫn đến chia ly.",
      "Xuất hành": "Không nên đi xa, dễ gặp hiểm nguy dọc đường hoặc trễ nải sự việc."
    },
    details_en: {
      "Personal": "Destiny is weak. Beware of petty people causing harm and gossip surrounding you.",
      "Home & Family": "Discord at home. Guard against theft and loss of possessions.",
      "Plans & Career": "Success is difficult. Projects may stall or collapse — postpone them.",
      "Wealth": "Finances depleted, prone to losses. Absolutely avoid lending money.",
      "Health": "Watch for serious illness, guard against unexpected accidents. Get medical checkups.",
      "Marriage": "Many obstacles, intense conflicts, risk of separation.",
      "Travel": "Do not travel far. Danger on the road or delays in important matters."
    }
  },
  {
    id: 5,
    name: "Quẻ Số 5 - Hạ Cát",
    name_en: "Stick #5 - Below Average",
    title: "Khổ Tận Cam Lai",
    title_en: "Bitterness Ends, Sweetness Arrives",
    poem: "Khổ tận cam lai sự tự thành\nNhất trùng vân khải nhất trùng thanh\nLịch tận gian nan quân tu ký\nKim triều đắc ý bộ bồng doanh.",
    poem_en: "Khổ tận cam lai sự tự thành\nNhất trùng vân khải nhất trùng thanh\nLịch tận gian nan quân tu ký\nKim triều đắc ý bộ bồng doanh.",
    translation: "Hết khổ tới sướng việc tự thành,\nMột tầng mây mở ra một tầng trời trong xanh.\nTrải hết gian nan người nên nhớ,\nSáng nay đắc ý bước lên chốn bồng lai.",
    translation_en: "When suffering ends, sweetness follows and things accomplish themselves,\nAs each layer of clouds parts, a clear blue sky is revealed.\nHaving endured all hardships, remember this well,\nToday you stride triumphantly into paradise.",
    meaning: "Tiền cát hậu hung, ban đầu gặp nhiều gian truân thử thách nhưng kiên trì đến cùng sẽ đạt được thành quả ngọt ngào.",
    meaning_en: "Difficult beginnings but sweet endings. Initial trials and tribulations will yield sweet results for those who persevere to the end.",
    details: {
      "Bản thân": "Trải qua thử thách giúp bản thân trưởng thành, vận khí dần dần tốt lên.",
      "Gia trạch": "Gia đạo ban đầu có chút bất hòa, sau đó mọi người thấu hiểu và đùm bọc nhau.",
      "Mưu sự": "Gặp nhiều trở ngại lúc đầu, kiên trì không bỏ cuộc chắc chắn sẽ thành.",
      "Cầu tài": "Tiền tài tích lũy từ từ, ban đầu khó khăn nhưng về sau khấm khá.",
      "Tật bệnh": "Bệnh tật dai dẳng nhưng gặp thầy gặp thuốc sẽ khỏi hoàn toàn.",
      "Hôn nhân": "Trải qua sóng gió thử thách mới đến được với nhau, tình cảm bền chặt.",
      "Xuất hành": "Ban đầu đi xa có chút trục trặc, sau đó mọi việc suôn sẻ thuận lợi."
    },
    details_en: {
      "Personal": "Trials help you grow stronger. Fortune gradually improves over time.",
      "Home & Family": "Some initial discord, but family members will come to understand and support each other.",
      "Plans & Career": "Many obstacles at first. Persist without giving up and success is certain.",
      "Wealth": "Wealth accumulates slowly. Difficult at first but prosperous later.",
      "Health": "Lingering illness, but the right doctor and medicine will bring complete recovery.",
      "Marriage": "Must weather storms and trials before finding each other. The bond will be strong.",
      "Travel": "Initial travel hiccups, but everything smooths out afterward."
    }
  },
  {
    id: 6,
    name: "Quẻ Số 6 - Trung Cát",
    name_en: "Stick #6 - Good Fortune",
    title: "Nhân Duyên Hòa Hợp",
    title_en: "Harmonious Human Bonds",
    poem: "Nhân duyên hòa hợp sự giai thông\nMộc dục xuân phong kiến thái hồng\nHỷ tín trùng phùng tăng phước lộc\nGia môn hòa khí tự hưng long.",
    poem_en: "Nhân duyên hòa hợp sự giai thông\nMộc dục xuân phong kiến thái hồng\nHỷ tín trùng phùng tăng phước lộc\nGia môn hòa khí tự hưng long.",
    translation: "Nhân duyên hòa hợp mọi việc đều thông suốt,\nTắm mát trong gió xuân nhìn thấy cầu vồng đẹp.\nTin vui gặp lại tăng thêm phước lộc,\nGia môn hòa thuận tự nhiên hưng thịnh.",
    translation_en: "When human bonds harmonize, all affairs flow smoothly,\nBathing in spring breezes, a beautiful rainbow appears.\nJoyful tidings reunite, blessings and fortune multiply,\nA harmonious household naturally prospers.",
    meaning: "Mọi sự tiến triển tốt đẹp nhờ sự hòa hợp và giúp đỡ của những người xung quanh. Gia đạo yên vui, công việc thuận lợi.",
    meaning_en: "All progresses well thanks to harmony and help from those around you. Family is joyful, work goes smoothly.",
    details: {
      "Bản thân": "Được mọi người yêu mến, nhân duyên tốt đẹp, tâm tình vui vẻ cát tường.",
      "Gia trạch": "Gia đạo yên vui, vợ chồng hòa thuận, có bạn bè tốt ghé thăm.",
      "Mưu sự": "Nên hợp tác làm ăn, hợp tác sẽ thành công lớn hơn làm một mình.",
      "Cầu tài": "Tài lộc khá tốt, tiền của đến từ các mối quan hệ hợp tác uy tín.",
      "Tật bệnh": "Sức khỏe ổn định, tinh thần sảng khoái giúp bệnh tật tiêu tan.",
      "Hôn nhân": "Nhân duyên rất tốt, đôi bên xứng lứa vừa đôi, sớm kết lương duyên.",
      "Xuất hành": "Xuất hành kết giao bạn bè hoặc gặp gỡ đối tác vô cùng thuận lợi."
    },
    details_en: {
      "Personal": "Beloved by all, excellent social connections, cheerful and auspicious spirits.",
      "Home & Family": "Household joyful, couple harmonious, good friends come visiting.",
      "Plans & Career": "Partnership is advised. Collaboration yields greater success than solo efforts.",
      "Wealth": "Good wealth prospects. Money comes through trusted partnerships.",
      "Health": "Health is stable. A cheerful spirit helps dispel illness.",
      "Marriage": "Excellent match. Both sides are well-suited — a good union will come soon.",
      "Travel": "Traveling to meet friends or business partners is extremely favorable."
    }
  },
  {
    id: 7,
    name: "Quẻ Số 7 - Thượng Thượng",
    name_en: "Stick #7 - Supreme Fortune",
    title: "Vân Khai Kiến Nhật",
    title_en: "Clouds Part to Reveal the Sun",
    poem: "Nhất phiến vân khai kiến thái dương\nVạn vật sinh huy chiếu tứ phương\nTự cổ nguy hiểm chung quá khứ\nKim triều hoạch cát đại cát tường.",
    poem_en: "Nhất phiến vân khai kiến thái dương\nVạn vật sinh huy chiếu tứ phương\nTự cổ nguy hiểm chung quá khứ\nKim triều hoạch cát đại cát tường.",
    translation: "Một áng mây mở nhìn thấy mặt trời,\nVạn vật tỏa sáng chiếu khắp ấm bốn phương.\nTự cổ hiểm nguy rồi cũng qua đi,\nHôm nay nhận được điều lành, đại cát tường.",
    translation_en: "A single cloud parts to reveal the glorious sun,\nAll things radiate light, warming the four directions.\nSince ancient times, dangers have always passed,\nToday brings great blessings — most auspicious fortune.",
    meaning: "Thời kỳ đen tối trắc trở đã qua, vận hội mới rực rỡ đã tới. Mọi việc bắt đầu phát triển cực kỳ mạnh mẽ.",
    meaning_en: "The dark times of hardship have passed, a brilliant new era has arrived. All things begin to develop with tremendous momentum.",
    details: {
      "Bản thân": "Vận khí bừng sáng, tai qua nạn khỏi, danh tiếng vang xa.",
      "Gia trạch": "Gia đạo gặp nhiều may mắn, giải quyết được các hiểu lầm tích tụ lâu nay.",
      "Mưu sự": "Gặp cơ hội vàng, hành động ngay lập tức sẽ đạt thành tựu đột phá.",
      "Cầu tài": "Tài lộc dồi dào, tiền bạc tự chảy vào túi, cơ hội trúng số hoặc thưởng lớn.",
      "Tật bệnh": "Bệnh nặng chuyển nhẹ, bệnh nhẹ tiêu trừ, cơ thể hồi phục nhanh chóng.",
      "Hôn nhân": "Tình duyên đơm hoa kết trái, đón hỷ sự lâm môn.",
      "Xuất hành": "Xuất hành đại cát, đi về hướng Đông hoặc hướng Nam có tài lộc lớn."
    },
    details_en: {
      "Personal": "Fortune blazes bright, calamities pass, reputation spreads far.",
      "Home & Family": "Family enjoys great luck, long-standing misunderstandings finally resolved.",
      "Plans & Career": "A golden opportunity appears. Act immediately for breakthrough achievements.",
      "Wealth": "Abundant wealth, money flows in naturally. Chance of lottery or big bonuses.",
      "Health": "Serious illness becomes mild, mild illness disappears. Body recovers rapidly.",
      "Marriage": "Romance blossoms and bears fruit. Joyous celebrations arrive at the doorstep.",
      "Travel": "Travel is supremely auspicious. East or south direction brings great wealth."
    }
  },
  {
    id: 8,
    name: "Quẻ Số 8 - Hạ Hạ",
    name_en: "Stick #8 - Misfortune",
    title: "Hổ Lạc Bình Dương",
    title_en: "Tiger Fallen on the Plains",
    poem: "Hổ lạc bình dương bị khuyển khi\nAnh hùng vô thế lẫm nan quy\nThời bất ngã dữ đa phòng hoạn\nTĩnh thủ duy trì tiệm khả vi.",
    poem_en: "Hổ lạc bình dương bị khuyển khi\nAnh hùng vô thế lẫm nan quy\nThời bất ngã dữ đa phòng hoạn\nTĩnh thủ duy trì tiệm khả vi.",
    translation: "Cọp xuống đồng bằng bị chó khinh,\nAnh hùng mất thế khó quay về.\nThời không đợi ta, nên phòng họa,\nYên lặng giữ mình, đợi cơ hội sau.",
    translation_en: "A tiger fallen on the plains is scorned by dogs,\nA hero without power finds it hard to return.\nTime waits for no one — guard against misfortune,\nQuietly hold your ground and wait for better days.",
    meaning: "Đang ở thế yếu, không có thời cơ thích hợp, dễ bị người dưới vượt mặt hoặc bắt chẹt. Đòi hỏi sự nhẫn nại cao độ.",
    meaning_en: "You are in a position of weakness without favorable timing. Others may surpass or take advantage of you. Great patience is required.",
    details: {
      "Bản thân": "Bị hạn chế tài năng, đề phòng thị phi tai tiếng, hạn chế tranh cãi.",
      "Gia trạch": "Gia đạo bất an, có xáo trộn nhỏ, đề phòng người ngoài gây chia rẽ.",
      "Mưu sự": "Chưa phải lúc thực hiện dự án mới, nên học hỏi thêm và giữ vững việc cũ.",
      "Cầu tài": "Không có tài lộc, dễ bị lừa gạt mất mát, hạn chế đầu tư rủi ro cao.",
      "Tật bệnh": "Cần cẩn thận các bệnh về xương khớp hoặc hô hấp, đề phòng té ngã.",
      "Hôn nhân": "Tình cảm rạn nứt do thiếu tin tưởng, dễ xảy ra cự cãi tranh chấp.",
      "Xuất hành": "Tránh đi xa, dễ gặp bất lợi về giấy tờ hoặc gặp kẻ xấu phá hoại."
    },
    details_en: {
      "Personal": "Talents are constrained. Guard against gossip and scandal, avoid arguments.",
      "Home & Family": "Household uneasy with minor disruptions. Beware outsiders sowing discord.",
      "Plans & Career": "Not the time for new projects. Learn more and maintain current work.",
      "Wealth": "No financial fortune. Risk of fraud and losses — avoid high-risk investments.",
      "Health": "Be careful of bone/joint or respiratory issues. Guard against falls.",
      "Marriage": "Relationship cracking from lack of trust. Prone to quarrels and disputes.",
      "Travel": "Avoid long trips. Risk of paperwork problems or encountering ill-intentioned people."
    }
  },
  {
    id: 9,
    name: "Quẻ Số 9 - Trung Bình",
    name_en: "Stick #9 - Average Fortune",
    title: "Nguyệt Lão Đàm Tâm",
    title_en: "The Moon Elder's Heart-to-Heart",
    poem: "Vân tiêu vụ tán nguyệt trùng minh\nTự nhiên chiếu đắc thế nhân tinh\nĐộc bộ hàn giang tuy cô độc\nChung hữu quý nhân chỉ lộ trình.",
    poem_en: "Vân tiêu vụ tán nguyệt trùng minh\nTự nhiên chiếu đắc thế nhân tinh\nĐộc bộ hàn giang tuy cô độc\nChung hữu quý nhân chỉ lộ trình.",
    translation: "Mây tan sương tạnh trăng lại sáng,\nTự nhiên soi tỏ khắp thế gian.\nMột mình qua sông lạnh tuy cô độc,\nCuối cùng vẫn có quý nhân chỉ đường đi.",
    translation_en: "Clouds disperse and mist clears, the moon shines bright once more,\nNaturally illuminating all the world below.\nCrossing the cold river alone may feel lonely,\nBut ultimately a noble benefactor will show the way.",
    meaning: "Giai đoạn chuyển giao từ khó khăn sang thuận lợi. Dù hiện tại có chút đơn độc nhưng sẽ sớm gặp được người giúp đỡ.",
    meaning_en: "A transitional period from difficulty to ease. Though currently somewhat alone, a helpful person will soon appear.",
    details: {
      "Bản thân": "Tâm trí sáng suốt, tự tìm ra lối thoát cho bản thân sau chuỗi ngày bế tắc.",
      "Gia trạch": "Gia đạo yên ổn, mọi xích mích nhỏ đều được hòa giải êm đẹp.",
      "Mưu sự": "Mở rộng kinh doanh cần thận trọng, tự lực cánh sinh là chính.",
      "Cầu tài": "Tài lộc bình thường, thu chi cân đối, không lo túng thiếu.",
      "Tật bệnh": "Chú ý giữ gìn sức khỏe khi thời tiết thay đổi, không có gì đáng lo.",
      "Hôn nhân": "Tình duyên tự đến dù muộn màng, cần kiên trì chân thành.",
      "Xuất hành": "Xuất hành hướng Tây Bắc sẽ gặp quý nhân hỗ trợ công việc."
    },
    details_en: {
      "Personal": "Mind is clear and sharp. You'll find your own way out after days of stagnation.",
      "Home & Family": "Household stable. Minor frictions are peacefully resolved.",
      "Plans & Career": "Business expansion requires caution. Self-reliance is key.",
      "Wealth": "Average wealth. Income and expenses balanced, no worries of shortage.",
      "Health": "Mind your health during weather changes. Nothing serious to worry about.",
      "Marriage": "Love will come naturally though perhaps late. Sincerity and patience are needed.",
      "Travel": "Traveling northwest will bring a noble benefactor who aids your work."
    }
  },
  {
    id: 10,
    name: "Quẻ Số 10 - Thượng Cát",
    name_en: "Stick #10 - Great Fortune",
    title: "Hỷ Khí Lâm Môn",
    title_en: "Joy Arrives at the Doorstep",
    poem: "Nguyệt lão đề hồng hỷ tự lai\nNhân hòa địa lợi vận đào khai\nGia môn cát khánh trùng trùng chí\nTài lộc song toàn tiếu nhan khai.",
    poem_en: "Nguyệt lão đề hồng hỷ tự lai\nNhân hòa địa lợi vận đào khai\nGia môn cát khánh trùng trùng chí\nTài lộc song toàn tiếu nhan khai.",
    translation: "Nguyệt lão se duyên hỷ tự tới,\nNhân hòa địa lợi vận đào hoa nở.\nGia đình cát khánh trùng trùng đến,\nTài lộc song toàn mặt rạng rỡ nụ cười.",
    translation_en: "The Moon Elder ties the red thread of fate, joy arrives on its own,\nPeople harmonious, land favorable, romance blossoms.\nFamily celebrations come one after another,\nWealth and fortune complete, faces beaming with smiles.",
    meaning: "Vận đào hoa cực vượng, nhân duyên tốt đẹp, gia đạo có hỷ sự. Cầu tài cầu lộc đều viên mãn.",
    meaning_en: "Romance flourishes greatly, excellent human connections, family celebrations abound. Seeking wealth or fortune — both are fulfilled.",
    details: {
      "Bản thân": "Bản mệnh hanh thông, thần thái tươi tắn, gặp nhiều may mắn trong các mối quan hệ.",
      "Gia trạch": "Gia môn có tin hỷ (cưới hỏi, sinh con), không khí gia đình rộn rã niềm vui.",
      "Mưu sự": "Thuận lợi nhờ tìm được đối tác ăn ý hoặc được mọi người đồng lòng ủng hộ.",
      "Cầu tài": "Tài lộc hanh thông, thu hoạch ngoài mong đợi, buôn bán đắt hàng.",
      "Tật bệnh": "Sức khỏe dồi dào, tràn đầy năng lượng tích cực.",
      "Hôn nhân": "Hôn nhân như ý, đôi lứa hạnh phúc, vợ chồng tình cảm mặn nồng.",
      "Xuất hành": "Xuất hành vô cùng cát lợi, dễ kết giao được tri kỷ hoặc đối tác lớn."
    },
    details_en: {
      "Personal": "Fortune flows smoothly, radiant demeanor, lucky in all relationships.",
      "Home & Family": "Joyful family news (weddings, births). Household buzzing with happiness.",
      "Plans & Career": "Favorable thanks to finding the right partner or earning unanimous support.",
      "Wealth": "Wealth flowing well, harvest beyond expectations, business booming.",
      "Health": "Abundant health, full of positive energy.",
      "Marriage": "Marriage as desired, couple happy, love deep and passionate.",
      "Travel": "Travel is extremely auspicious. Easy to make soulmates or major business partners."
    }
  },
  {
    id: 11,
    name: "Quẻ Số 11 - Trung Bình",
    name_en: "Stick #11 - Average Fortune",
    title: "Thủ Cựu An Phận",
    title_en: "Keep the Old, Accept Your Lot",
    poem: "Tùy duyên an phận thủ cựu nghiệp\nMạc si ngã tưởng vọng phi thiên\nTự hữu sinh cơ lai chiếu cố\nBình an nhị tự trị thiên kim.",
    poem_en: "Tùy duyên an phận thủ cựu nghiệp\nMạc si ngã tưởng vọng phi thiên\nTự hữu sinh cơ lai chiếu cố\nBình an nhị tự trị thiên kim.",
    translation: "Tùy duyên an phận giữ nghiệp cũ,\nChớ ham tưởng hão bay lên trời.\nTự có sinh cơ đến chiếu cố,\nHai chữ bình an đáng giá ngàn vàng.",
    translation_en: "Follow fate, accept your lot, and guard the old profession,\nDo not indulge in fantasies of flying to the heavens.\nOpportunity will naturally come to look after you,\nThe two words 'peace and safety' are worth a thousand gold.",
    meaning: "Không nên có những mong muốn viển vông hay thay đổi công việc hiện tại. Hãy trân trọng sự bình an đang có.",
    meaning_en: "Do not harbor unrealistic desires or change your current path. Cherish the peace you already have.",
    details: {
      "Bản thân": "Nên tu tâm dưỡng tính, hài lòng với những gì mình đang có.",
      "Gia trạch": "Gia đạo êm đềm bình an, không xảy ra biến cố gì lớn.",
      "Mưu sự": "Không thích hợp khởi nghiệp hay đổi việc, tiếp tục làm công việc cũ sẽ có kết quả tốt.",
      "Cầu tài": "Tài lộc ổn định, tránh đầu tư mạo hiểm kẻo tiền mất tật mang.",
      "Tật bệnh": "Chú ý chăm sóc bản thân, tránh lao lực quá độ.",
      "Hôn nhân": "Tình cảm bình dị, chân chất, không có nhiều lãng mạn nhưng rất vững bền.",
      "Xuất hành": "Không nên xuất hành đi xa vào lúc này, ở nhà an toàn hơn."
    },
    details_en: {
      "Personal": "Cultivate inner peace and be content with what you have.",
      "Home & Family": "Household peaceful and calm. No major incidents to worry about.",
      "Plans & Career": "Not suitable for starting businesses or changing jobs. Continuing current work yields good results.",
      "Wealth": "Stable finances. Avoid risky investments lest you lose both money and health.",
      "Health": "Take care of yourself and avoid overwork.",
      "Marriage": "Love is simple and genuine — not very romantic but very enduring.",
      "Travel": "Best not to travel far at this time. Staying home is safer."
    }
  },
  {
    id: 12,
    name: "Quẻ Số 12 - Thượng Thượng",
    name_en: "Stick #12 - Supreme Fortune",
    title: "Ngư Dược Long Môn",
    title_en: "The Carp Leaps Over Dragon Gate",
    poem: "Long môn đắc ý bộ vân tiêu\nVạn lý giang sơn nhậm ngã tiêu\nPhong vân hội hợp cơ duyên chí\nNhất cử thành danh thiên hạ kiêu.",
    poem_en: "Long môn đắc ý bộ vân tiêu\nVạn lý giang sơn nhậm ngã tiêu\nPhong vân hội hợp cơ duyên chí\nNhất cử thành danh thiên hạ kiêu.",
    translation: "Long môn đắc ý bước chín tầng mây,\nVạn dặm non sông thỏa sức vẫy vùng.\nRồng mây hội tụ cơ duyên tới,\nMột bước thành danh cả thiên hạ tự hào.",
    translation_en: "At Dragon Gate, stepping triumphantly into the nine-layered clouds,\nAcross ten thousand miles of rivers and mountains, free to roam.\nWind and clouds converge as destiny's moment arrives,\nIn one leap, fame is won and the whole world takes pride.",
    meaning: "Đỉnh cao của sự nghiệp và danh vọng. Cơ hội hiếm có để thay đổi hoàn toàn cuộc đời theo hướng tốt đẹp nhất.",
    meaning_en: "The pinnacle of career and prestige. A rare opportunity to completely transform your life for the better.",
    details: {
      "Bản thân": "Vận khí cực kỳ hanh thông, học hành thi cử đỗ đầu, thăng tiến vượt bậc.",
      "Gia trạch": "Gia tộc vẻ quang, rạng danh tổ tông, con cháu hiển đạt.",
      "Mưu sự": "Mọi kế hoạch lớn lao đều thành công rực rỡ, được xã hội công nhận.",
      "Cầu tài": "Tài lộc phát đạt vô số, tiền bạc dư dả dư của ăn của để.",
      "Tật bệnh": "Cơ thể khỏe mạnh lực lưỡng, bệnh cũ biến mất hoàn toàn.",
      "Hôn nhân": "Kết hôn với người môn đăng hộ đối, vợ chồng vinh hiển cùng nhau.",
      "Xuất hành": "Xuất hành vô cùng thuận lợi và vinh quang, có lợi cho công danh."
    },
    details_en: {
      "Personal": "Fortune at its absolute peak. Exams passed with top honors, rapid career advancement.",
      "Home & Family": "Family pride and glory, ancestors honored, descendants distinguished.",
      "Plans & Career": "All grand plans succeed brilliantly, earning societal recognition.",
      "Wealth": "Limitless wealth and fortune, money in abundant surplus.",
      "Health": "Body strong and vigorous, old ailments vanish completely.",
      "Marriage": "Marry someone of equal standing. Couple shares glory together.",
      "Travel": "Travel is supremely smooth and glorious, beneficial for career advancement."
    }
  },
  {
    id: 13,
    name: "Quẻ Số 13 - Hạ Hạ",
    name_en: "Stick #13 - Misfortune",
    title: "Thuyền Lậu Phong Cấp",
    title_en: "A Leaking Boat in Fierce Winds",
    poem: "Thuyền lậu phùng phong cấp thủy hành\nGia sơn vạn lý mịch vô trình\nTạm thời tránh nạn vô phương tiến\nTĩnh đãi triều bình thủy thế thanh.",
    poem_en: "Thuyền lậu phùng phong cấp thủy hành\nGia sơn vạn lý mịch vô trình\nTạm thời tránh nạn vô phương tiến\nTĩnh đãi triều bình thủy thế thanh.",
    translation: "Thuyền thủng gặp gió giữa dòng nước chảy xiết,\nQuê nhà vạn dặm mờ mịt không thấy đường về.\nTạm thời lánh nạn không thể tiến lên,\nYên lặng đợi triều dâng sóng lặng nước trong xanh.",
    translation_en: "A leaking boat meets fierce winds on rushing waters,\nHomeland ten thousand miles away, the path invisible.\nTemporarily seek shelter — there is no way forward,\nQuietly wait for the tide to calm and waters to clear.",
    meaning: "Họa vô đơn chí, khó khăn chồng chất khó khăn. Cần tuyệt đối dừng mọi hoạt động lớn, tìm nơi trú ẩn an toàn.",
    meaning_en: "Misfortunes never come alone — difficulties pile upon difficulties. Absolutely cease all major activities and seek safe shelter.",
    details: {
      "Bản thân": "Bản mệnh gặp nguy nan, đề phòng tai bay vạ gió, tránh xa thị phi pháp luật.",
      "Gia trạch": "Gia đình gặp biến cố lớn hoặc hao tài tốn của nghiêm trọng.",
      "Mưu sự": "Dự án thất bại thảm hại, tránh đầu tư thêm để gỡ gạc kẻo mất trắng.",
      "Cầu tài": "Nợ nần chồng chất hoặc thất thoát tiền của lớn, hãy thắt lưng buộc bụng.",
      "Tật bệnh": "Bệnh tình nguy kịch, cần điều trị tích cực ngay lập tức.",
      "Hôn nhân": "Đôi bên mâu thuẫn gay gắt dẫn đến đổ vỡ, khó lòng hàn gắn.",
      "Xuất hành": "Cấm kỵ đi xa, đi sông nước rất nguy hiểm, nên ở nhà."
    },
    details_en: {
      "Personal": "Destiny faces great peril. Guard against unexpected disasters and stay away from legal disputes.",
      "Home & Family": "Family faces major upheaval or serious financial losses.",
      "Plans & Career": "Projects fail catastrophically. Don't invest more trying to recover — you'll lose everything.",
      "Wealth": "Debts pile up or major financial losses occur. Tighten your belt.",
      "Health": "Health is critical. Seek aggressive treatment immediately.",
      "Marriage": "Intense conflicts between both sides leading to collapse. Very difficult to repair.",
      "Travel": "Absolutely forbidden to travel far. Water travel is especially dangerous. Stay home."
    }
  },
  {
    id: 14,
    name: "Quẻ Số 14 - Trung Cát",
    name_en: "Stick #14 - Good Fortune",
    title: "Gia Môn Hưng Thịnh",
    title_en: "Household Prosperity Flourishes",
    poem: "Gia môn thanh cát khánh dư sinh\nTứ quý bình an lộc tự sinh\nThường hành thiện sự thiên quân chiếu\nVạn sự vô ưu đắc thái bình.",
    poem_en: "Gia môn thanh cát khánh dư sinh\nTứ quý bình an lộc tự sinh\nThường hành thiện sự thiên quân chiếu\nVạn sự vô ưu đắc thái bình.",
    translation: "Cửa nhà yên ổn chúc mừng đời ta,\nBốn mùa bình an tự sinh tài lộc.\nThường làm việc thiện trời cao chiếu cố,\nVạn sự không lo, hưởng thái bình.",
    translation_en: "Home is peaceful, celebrating life's blessings,\nFour seasons of safety, fortune naturally arises.\nRegularly doing good deeds earns heaven's favor,\nAll matters worry-free, enjoying lasting peace.",
    meaning: "Gia đạo yên bình, cuộc sống êm ấm nhờ tích đức hành thiện. Tài lộc tự nhiên đưa tới không cần cầu cạnh.",
    meaning_en: "Family life is peaceful and warm thanks to accumulated good deeds. Fortune arrives naturally without needing to seek it.",
    details: {
      "Bản thân": "Tâm tính hướng thiện, cuộc sống an nhàn, không gặp sóng gió lớn.",
      "Gia trạch": "Gia đạo hòa thuận, anh em kính nhường, con cái ngoan ngoãn hiếu thảo.",
      "Mưu sự": "Mưu sự thuận lợi nhờ sự lương thiện và trung thực của bản thân.",
      "Cầu tài": "Tài lộc ở mức khá, tiền bạc đến chậm nhưng chắc chắn và bền vững.",
      "Tật bệnh": "Sức khỏe tốt, ít ốm đau bệnh tật vặt.",
      "Hôn nhân": "Gia đình êm ấm, vợ chồng thủy chung, tôn trọng lẫn nhau.",
      "Xuất hành": "Nên đi du lịch gia đình hoặc đi lễ chùa cầu an rất tốt."
    },
    details_en: {
      "Personal": "Kind-hearted nature, leisurely life, no major storms.",
      "Home & Family": "Harmonious family, siblings respectful, children obedient and filial.",
      "Plans & Career": "Plans succeed thanks to personal honesty and integrity.",
      "Wealth": "Good finances. Money comes slowly but surely and sustainably.",
      "Health": "Good health with few minor ailments.",
      "Marriage": "Warm family, faithful couple, mutual respect.",
      "Travel": "Family trips or temple visits for blessings are highly recommended."
    }
  },
  {
    id: 15,
    name: "Quẻ Số 15 - Thượng Cát",
    name_en: "Stick #15 - Great Fortune",
    title: "Kim Bảng Đề Danh",
    title_en: "Name Inscribed on the Golden Board",
    poem: "Kim bảng đề danh tự hữu thời\nThập niên hàn song khởi vô tri\nThời lai phong tống đằng vân khứ\nNhất bộ cao thăng lập vạn kỳ.",
    poem_en: "Kim bảng đề danh tự hữu thời\nThập niên hàn song khởi vô tri\nThời lai phong tống đằng vân khứ\nNhất bộ cao thăng lập vạn kỳ.",
    translation: "Bảng vàng khắc tên tự có lúc,\nMười năm đèn sách há vô danh.\nThời tới gió đưa bay lên mây,\nMột bước thăng cao lập kỳ tích vạn đời.",
    translation_en: "Your name on the golden board — its time will come,\nTen years of studious toil shall not be in vain.\nWhen the time arrives, the wind carries you soaring through clouds,\nOne step to great heights, establishing a legacy for all ages.",
    meaning: "Sự cố gắng kiên trì suốt thời gian qua sắp được đền đáp xứng đáng. Công danh sự nghiệp thăng tiến.",
    meaning_en: "Your persistent efforts over time are about to be justly rewarded. Career and prestige are ascending.",
    details: {
      "Bản thân": "Học hành tấn tới, thi cử đỗ đạt cao, năng lực được công nhận.",
      "Gia trạch": "Gia đình tự hào về thành tựu của bạn, gia đạo vẻ vang.",
      "Mưu sự": "Thăng tiến trong công việc, ký kết được các hợp đồng lớn quan trọng.",
      "Cầu tài": "Tài lộc dồi dào nhờ công danh mang lại, lương thưởng tăng cao.",
      "Tật bệnh": "Tinh thần phấn chấn giúp cơ thể khỏe mạnh dẻo dai.",
      "Hôn nhân": "Đôi bên môn đăng hộ đối, cùng tiến bước xây dựng tương lai.",
      "Xuất hành": "Xuất hành đi thi cử, phỏng vấn hoặc nhận chức vô cùng cát lợi."
    },
    details_en: {
      "Personal": "Studies advance, exams passed with high marks, abilities recognized.",
      "Home & Family": "Family proud of your achievements, household honored.",
      "Plans & Career": "Career promotion, major contracts and important deals signed.",
      "Wealth": "Abundant wealth from career success. Salary and bonuses increase.",
      "Health": "High spirits keep the body healthy and resilient.",
      "Marriage": "Well-matched couple, building the future together.",
      "Travel": "Traveling for exams, interviews, or inaugurations is supremely auspicious."
    }
  },
  {
    id: 16,
    name: "Quẻ Số 16 - Hạ Cát",
    name_en: "Stick #16 - Below Average",
    title: "Mai Khai Trong Tuyết",
    title_en: "Plum Blossoms Blooming in Snow",
    poem: "Tuyết lý mai hoa tiệm tiệm khai\nGian nan lịch tận cát tường lai\nMặc đãi hàn phong tiêu tán tận\nTự hữu xuân quang báo hỷ đài.",
    poem_en: "Tuyết lý mai hoa tiệm tiệm khai\nGian nan lịch tận cát tường lai\nMặc đãi hàn phong tiêu tán tận\nTự hữu xuân quang báo hỷ đài.",
    translation: "Hoa mai trong tuyết hé nở dần,\nGian nan trải hết điều lành tới.\nĐợi cho gió lạnh tan biến hết,\nTự có ánh xuân báo tin vui về.",
    translation_en: "Plum blossoms in the snow gradually begin to open,\nWhen hardships have been endured, good fortune arrives.\nWait for the cold winds to completely dissipate,\nSpring's light will naturally bring tidings of joy.",
    meaning: "Khó khăn sắp kết thúc, hy vọng mới đang nhen nhóm dần. Cần kiên nhẫn vượt qua chặng cuối cùng.",
    meaning_en: "Difficulties are nearing their end, new hope is gradually kindling. Patience is needed to get through the final stretch.",
    details: {
      "Bản thân": "Bản thân cần kiên nhẫn chịu đựng thử thách cuối cùng trước khi hái quả ngọt.",
      "Gia trạch": "Gia đạo dần dần ổn định sau những xung đột, ấm áp trở lại.",
      "Mưu sự": "Công việc bắt đầu có tiến triển khả quan, hướng đi mới đúng đắn.",
      "Cầu tài": "Tài lộc bắt đầu khởi sắc, tiền bạc dần dư dả hơn trước.",
      "Tật bệnh": "Bệnh tình chuyển biến tốt dần lên, chú ý giữ ấm cơ thể.",
      "Hôn nhân": "Tình cảm dần ấm lại sau thời gian nguội lạnh, hai bên hiểu nhau hơn.",
      "Xuất hành": "Đi xa có chút lạnh giá/khó khăn ban đầu, sau đó suôn sẻ."
    },
    details_en: {
      "Personal": "Patience is needed to endure the final trial before reaping sweet rewards.",
      "Home & Family": "Family gradually stabilizing after conflicts, warmth returning.",
      "Plans & Career": "Work begins showing promising progress. The new direction is correct.",
      "Wealth": "Finances starting to improve, money gradually becomes more plentiful.",
      "Health": "Health gradually improving. Keep the body warm.",
      "Marriage": "Feelings warming up again after a cold period. Both sides understand each other better.",
      "Travel": "Travel starts with some cold/difficulty but smooths out afterward."
    }
  },
  {
    id: 17,
    name: "Quẻ Số 17 - Trung Bình",
    name_en: "Stick #17 - Average Fortune",
    title: "Thạch Trung Ẩn Ngọc",
    title_en: "Jade Hidden within Stone",
    poem: "Thạch trung ẩn ngọc vị năng khai\nVạn sự tu phòng bất ý tai\nTĩnh tâm đãi thời cầu minh triết\nTự hữu quý nhân cổ vũ lai.",
    poem_en: "Thạch trung ẩn ngọc vị năng khai\nVạn sự tu phòng bất ý tai\nTĩnh tâm đãi thời cầu minh triết\nTự hữu quý nhân cổ vũ lai.",
    translation: "Trong đá ẩn ngọc chưa thể khai thác,\nMọi việc nên phòng tai họa bất ngờ.\nTĩnh tâm đợi thời cầu trí tuệ,\nTự có quý nhân đến cổ vũ giúp sức.",
    translation_en: "Jade hidden within stone cannot yet be mined,\nIn all matters guard against unexpected calamity.\nCalm the mind, wait for the right time, and seek wisdom,\nA noble benefactor will naturally come to encourage and help.",
    meaning: "Tài năng hay cơ hội đang bị che giấu, chưa lộ diện rõ ràng. Cần trau dồi bản thân thêm và chờ người hiền mắt tinh phát hiện.",
    meaning_en: "Talent or opportunity is hidden, not yet revealed clearly. Continue to refine yourself and wait for a wise person to discover your worth.",
    details: {
      "Bản thân": "Bản thân có năng lực nhưng chưa được trọng dụng, chớ nên nản lòng.",
      "Gia trạch": "Gia đạo bình an, cuộc sống không quá giàu sang nhưng êm ấm.",
      "Mưu sự": "Chưa thích hợp khởi đầu việc mới hoành tráng, hãy chuẩn bị kỹ lưỡng trước.",
      "Cầu tài": "Tài lộc tiềm ẩn, chưa thu hoạch ngay được, đầu tư dài hạn thì tốt.",
      "Tật bệnh": "Đề phòng bệnh ngầm trong cơ thể, nên đi khám sức khỏe tổng quát.",
      "Hôn nhân": "Đối phương là người tốt nhưng kín tiếng, cần thời gian tìm hiểu sâu hơn.",
      "Xuất hành": "Xuất hành bình thường, đi xa không có nhiều lợi lộc."
    },
    details_en: {
      "Personal": "You have ability but it's not yet recognized. Don't be discouraged.",
      "Home & Family": "Household peaceful. Life isn't lavish but is warm and comfortable.",
      "Plans & Career": "Not yet suitable for grand new ventures. Prepare thoroughly first.",
      "Wealth": "Hidden potential wealth. Cannot harvest immediately, but long-term investment is wise.",
      "Health": "Watch for hidden ailments. A comprehensive health checkup is recommended.",
      "Marriage": "Partner is a good person but reserved. More time is needed for deeper understanding.",
      "Travel": "Travel is average. Long trips don't bring much benefit."
    }
  },
  {
    id: 18,
    name: "Quẻ Số 18 - Thượng Thượng",
    name_en: "Stick #18 - Supreme Fortune",
    title: "Song Hỷ Lâm Môn",
    title_en: "Double Joy Arrives at the Door",
    poem: "Song hỷ lâm môn cát khánh lai\nGia tài vạn quán vạn hoa khai\nNhân hiền gia cát thiên sinh phúc\nVạn sự hanh thông lập thế đài.",
    poem_en: "Song hỷ lâm môn cát khánh lai\nGia tài vạn quán vạn hoa khai\nNhân hiền gia cát thiên sinh phúc\nVạn sự hanh thông lập thế đài.",
    translation: "Hai niềm vui cùng đến cửa mang điều lành,\nGia sản vạn quán trăm hoa đua nở.\nNgười hiền nhà tốt trời ban phước lớn,\nVạn sự hanh thông lập nên đại nghiệp.",
    translation_en: "Double joy arrives at the door bringing blessings,\nFamily fortune vast as ten thousand blooming flowers.\nVirtuous people in a good home — heaven bestows great blessings,\nAll matters flow smoothly, establishing a grand legacy.",
    meaning: "Đại cát đại lợi, hỷ sự nhân đôi, gia đình hưng vượng giàu sang cát tường.",
    meaning_en: "Greatly auspicious and profitable. Double celebrations, family thriving with wealth and blessings.",
    details: {
      "Bản thân": "May mắn ngập tràn, tinh thần vui vẻ phấn chấn tột đỉnh.",
      "Gia trạch": "Gia đạo vô cùng thịnh vượng, có cả tin hỷ về con cái lẫn tài sản.",
      "Mưu sự": "Thành công vang dội, mưu sự đạt kết quả mỹ mãn ngoài mong đợi.",
      "Cầu tài": "Tài lộc dồi dào, tiền bạc dâng tràn, đầu tư trúng lớn.",
      "Tật bệnh": "Khỏe mạnh hoàn hảo, không lo ốm đau bệnh tật.",
      "Hôn nhân": "Tình duyên đơm hoa kết trái ngọt ngào, cuộc sống lứa đôi hạnh phúc.",
      "Xuất hành": "Xuất hành đại cát, đi đâu cũng được cung đón kính trọng."
    },
    details_en: {
      "Personal": "Overflowing with luck. Spirits at their peak of joy and exhilaration.",
      "Home & Family": "Supremely prosperous household. Joyful news of both children and property.",
      "Plans & Career": "Resounding success. Plans exceed expectations magnificently.",
      "Wealth": "Abundant wealth, money overflowing. Investments hit big.",
      "Health": "Perfectly healthy. No worries of illness.",
      "Marriage": "Romance blossoms and bears sweet fruit. Couple's life is blissful.",
      "Travel": "Travel is supremely auspicious. Welcomed and respected wherever you go."
    }
  },
  {
    id: 19,
    name: "Quẻ Số 19 - Hạ Hạ",
    name_en: "Stick #19 - Misfortune",
    title: "Họa Vô Đơn Chí",
    title_en: "Misfortunes Never Come Alone",
    poem: "Họa vô đơn chí tích phòng thân\nThị phi khẩu thiệt nhiễu cô thần\nTu tâm hướng thiện tiêu tai họa\nMạc tín tha nhân vọng tự phân.",
    poem_en: "Họa vô đơn chí tích phòng thân\nThị phi khẩu thiệt nhiễu cô thần\nTu tâm hướng thiện tiêu tai họa\nMạc tín tha nhân vọng tự phân.",
    translation: "Họa không đến một lần, nên đề phòng thân,\nThị phi cự cãi quấy nhiễu thân cô độc.\nTu tâm hướng thiện để tiêu trừ tai họa,\nChớ tin người ngoài mà tự chia rẽ bè phái.",
    translation_en: "Misfortunes never come alone — protect yourself,\nGossip and slander harass your lonely soul.\nCultivate virtue and do good to dispel calamity,\nDo not trust outsiders who would sow division.",
    meaning: "Gặp vận hạn nặng, nhiều điều xui xẻo xảy ra cùng lúc. Cần thành tâm sám hối, tránh tranh chấp cự cãi.",
    meaning_en: "Facing heavy bad luck — many unfortunate events happen simultaneously. Sincerely repent and avoid disputes and arguments.",
    details: {
      "Bản thân": "Bản mệnh suy vi, dễ gặp hạn thị phi, kiện tụng hoặc tổn thương thân thể.",
      "Gia trạch": "Trong nhà lục đục, có kẻ tiểu nhân đơm đặt làm mất hòa khí.",
      "Mưu sự": "Tuyệt đối không bắt đầu dự án mới, rủi ro đổ vỡ rất cao.",
      "Cầu tài": "Hao tài tốn của nặng nề đề phòng lừa đảo mất mát tiền của lớn.",
      "Tật bệnh": "Dễ mắc bệnh dai dẳng khó chữa hoặc tai nạn, cần hết sức thận trọng.",
      "Hôn nhân": "Rạn nứt nghiêm trọng, dễ ly hôn ly thân, cần kiềm chế cái tôi.",
      "Xuất hành": "Không xuất hành đi xa, đi đứng cẩn thận xe cộ."
    },
    details_en: {
      "Personal": "Destiny declining. Prone to gossip, lawsuits, or physical harm.",
      "Home & Family": "Discord at home. Petty people fabricating stories to destroy harmony.",
      "Plans & Career": "Absolutely do not start new projects. Extremely high risk of collapse.",
      "Wealth": "Heavy financial losses. Guard against fraud and major monetary losses.",
      "Health": "Prone to chronic difficult-to-treat illness or accidents. Exercise extreme caution.",
      "Marriage": "Serious cracks, risk of divorce or separation. Control your ego.",
      "Travel": "Do not travel far. Be very careful with vehicles and traffic."
    }
  },
  {
    id: 20,
    name: "Quẻ Số 20 - Thượng Cát",
    name_en: "Stick #20 - Great Fortune",
    title: "Bình Bộ Thanh Vân",
    title_en: "Ascending to Blue Clouds Step by Step",
    poem: "Bình bộ thanh vân vạn lý trình\nThời lai vận chuyển khánh thiên thanh\nKim bảng đề danh gia cát thịnh\nCông danh phú quý lập tôn vinh.",
    poem_en: "Bình bộ thanh vân vạn lý trình\nThời lai vận chuyển khánh thiên thanh\nKim bảng đề danh gia cát thịnh\nCông danh phú quý lập tôn vinh.",
    translation: "Thong thả bước lên mây xanh đi vạn dặm,\nThời tới vận chuyển chúc mừng trời trong xanh.\nBảng vàng đề tên gia đình hưng thịnh,\nCông danh phú quý lập nên vinh quang tôn quý.",
    translation_en: "Leisurely ascending through blue clouds on a ten-thousand-mile journey,\nWhen fortune's time arrives, celebrating under clear blue skies.\nName inscribed on the golden board, family prospers,\nCareer, wealth, and prestige established in honored glory.",
    meaning: "Thời vận thăng tiến nhanh chóng và vững chắc, đạt được vị trí cao trong xã hội và giàu sang phú quý.",
    meaning_en: "Fortune ascends rapidly and firmly, achieving a high position in society with wealth and prestige.",
    details: {
      "Bản thân": "Vận khí cực thịnh, công danh hiển đạt, nhận được sự kính trọng lớn.",
      "Gia trạch": "Gia đạo yên ấm, hưng vượng, con cái đỗ đạt cao làm vẻ vang gia đình.",
      "Mưu sự": "Công việc thăng quan tiến chức, mở rộng kinh doanh đạt thắng lợi lớn.",
      "Cầu tài": "Tài lộc phú quý dồi dào, tiền của đến từ những nguồn chính đáng và vững chắc.",
      "Tật bệnh": "Cơ thể khỏe khoắn tinh thần minh mẫn sáng suốt.",
      "Hôn nhân": "Hôn nhân hạnh phúc viên mãn, vợ chồng cùng thăng tiến trong sự nghiệp.",
      "Xuất hành": "Xuất hành vô cùng thuận lợi và vinh quang, có lợi cho công danh."
    },
    details_en: {
      "Personal": "Fortune at peak prosperity, career distinguished, earning great respect.",
      "Home & Family": "Household warm and thriving. Children achieve high honors bringing family glory.",
      "Plans & Career": "Promotion and advancement at work. Business expansion achieves major victories.",
      "Wealth": "Abundant wealth and prestige from legitimate and solid sources.",
      "Health": "Body is strong and healthy, mind sharp and clear.",
      "Marriage": "Marriage perfectly fulfilled. Both partners advance together in their careers.",
      "Travel": "Travel is supremely favorable and glorious, beneficial for career advancement."
    }
  },
  {
    id: 21,
    name: "Quẻ Số 21 - Trung Bình",
    name_en: "Stick #21 - Average Fortune",
    title: "Cận Thủy Lâu Đài",
    title_en: "The Waterside Tower Gets Moonlight First",
    poem: "Cận thủy lâu đài tiên đắc nguyệt\nHướng dương hoa mộc dị vi xuân\nTự nhiên đắc lực vô đa lự\nTĩnh thủ gia môn phúc tự lân.",
    poem_en: "Cận thủy lâu đài tiên đắc nguyệt\nHướng dương hoa mộc dị vi xuân\nTự nhiên đắc lực vô đa lự\nTĩnh thủ gia môn phúc tự lân.",
    translation: "Lâu đài gần nước được trăng trước,\nCây cỏ hướng về phía mặt trời dễ đón xuân.\nTự nhiên đắc thế không cần lo nghĩ nhiều,\nYên lặng giữ cửa nhà phước đức tự đến bên.",
    translation_en: "The waterside tower receives the moonlight first,\nFlowers facing the sun welcome spring more easily.\nNaturally gaining advantage without excessive worry,\nQuietly guard the home and blessings will come on their own.",
    meaning: "Nhờ có lợi thế vị trí hoặc quan hệ tốt mà gặt hái thành công thuận lợi hơn người khác. Cần biết tận dụng thời cơ.",
    meaning_en: "Thanks to positional advantage or good connections, you can harvest success more easily than others. Know how to seize the moment.",
    details: {
      "Bản thân": "Gặp được thiên thời địa lợi, bản thân nhàn nhã mà vẫn đạt kết quả tốt.",
      "Gia trạch": "Gia môn yên ấm ổn định, có phúc khí tốt lành bao phủ.",
      "Mưu sự": "Thuận lợi tiến hành nhờ tận dụng được các mối quan hệ sẵn có.",
      "Cầu tài": "Tài lộc đều đặn ổn định, có lộc ăn lộc mặc phong phú.",
      "Tật bệnh": "Sức khỏe tốt, không có bệnh tật gì lớn.",
      "Hôn nhân": "Tình duyên êm đẹp, đôi bên thấu hiểu chia sẻ ngọt bùi.",
      "Xuất hành": "Nên đi du lịch ngắn ngày, đi xa vừa phải thì tốt hơn đi quá xa."
    },
    details_en: {
      "Personal": "Enjoying favorable timing and positioning. Achieving good results without much strain.",
      "Home & Family": "Household warm and stable, blessed with good fortune energy.",
      "Plans & Career": "Progress is smooth thanks to leveraging existing relationships.",
      "Wealth": "Steady and stable income, abundant blessings in food and clothing.",
      "Health": "Good health, no major illnesses.",
      "Marriage": "Harmonious romance, both sides understanding and sharing through thick and thin.",
      "Travel": "Short trips are recommended. Moderate distance is better than going too far."
    }
  },
  {
    id: 22,
    name: "Quẻ Số 22 - Hạ Cát",
    name_en: "Stick #22 - Below Average",
    title: "Bách Chiết Bất Quyên",
    title_en: "A Hundred Falls but Never Surrender",
    poem: "Bách chiết bất quyên chung hữu thành\nGian nan hiểm trở mạc sầu sinh\nTu tri thế sự đa mài luyện\nTự hữu sinh quang chiếu cẩm trình.",
    poem_en: "Bách chiết bất quyên chung hữu thành\nGian nan hiểm trở mạc sầu sinh\nTu tri thế sự đa mài luyện\nTự hữu sinh quang chiếu cẩm trình.",
    translation: "Trăm lần gãy không nản lòng cuối cùng sẽ thành,\nGian nan hiểm trở chớ lo âu phiền muộn sinh ra.\nNên biết việc đời nhiều mài giũa,\nTự có ánh sáng sinh cơ chiếu rọi đường gấm hoa.",
    translation_en: "Broken a hundred times yet never yielding — success will come at last,\nDo not let sorrow breed from hardships and dangers.\nKnow that life's affairs require much refining,\nA light of hope will naturally illuminate the brocade path ahead.",
    meaning: "Gặp nhiều gian nan vất vả, đòi hỏi ý chí kiên định 'thất bại là mẹ thành công'. Sự bền bỉ sẽ mang lại quả ngọt.",
    meaning_en: "Many hardships and toils ahead, demanding iron will. 'Failure is the mother of success.' Perseverance will bear sweet fruit.",
    details: {
      "Bản thân": "Cần trui rèn ý chí qua thử thách khó khăn, không được nản lòng thoái chí.",
      "Gia trạch": "Gia đạo tuy có chút trục trặc nhỏ nhưng mọi người yêu thương đùm bọc nhau.",
      "Mưu sự": "Gặp nhiều chướng ngại vật cản đường, đòi hỏi sự kiên trì bền bỉ vượt qua.",
      "Cầu tài": "Tài lộc có được bằng mồ hôi công sức tự thân vận động, không có lộc trời cho.",
      "Tật bệnh": "Bệnh tật cần kiên trì điều trị lâu dài mới mong khỏi hẳn.",
      "Hôn nhân": "Trải qua nhiều ngăn cấm trắc trở mới đến được với nhau, tình yêu bền chặt.",
      "Xuất hành": "Đi xa gặp chút khó khăn trở ngại ban đầu, kiên trì sẽ đạt được mục đích."
    },
    details_en: {
      "Personal": "Must forge willpower through difficult trials. Never lose heart or retreat.",
      "Home & Family": "Family has minor issues but everyone loves and supports each other.",
      "Plans & Career": "Many obstacles blocking the path. Persistent tenacity is required to overcome them.",
      "Wealth": "Wealth earned through sweat and personal effort — no heaven-sent fortune.",
      "Health": "Illness requires persistent long-term treatment for full recovery.",
      "Marriage": "Must overcome many prohibitions and obstacles before being together. Love is strong.",
      "Travel": "Travel encounters initial difficulties but persistence achieves the goal."
    }
  },
  {
    id: 23,
    name: "Quẻ Số 23 - Trung Cát",
    name_en: "Stick #23 - Good Fortune",
    title: "Thời Lai Vận Chuyển",
    title_en: "Fortune's Time Has Come",
    poem: "Thời lai vận chuyển tiệm hưng long\nVạn sự khai hoa tiệm tiệm thông\nTử khí đông lai tăng phước trạch\nGia môn hòa hỷ cát tinh tòng.",
    poem_en: "Thời lai vận chuyển tiệm hưng long\nVạn sự khai hoa tiệm tiệm thông\nTử khí đông lai tăng phước trạch\nGia môn hòa hỷ cát tinh tòng.",
    translation: "Thời tới vận chuyển dần hưng long,\nMọi việc nở hoa thông suốt dần.\nKhí lành phương đông tới tăng thêm phước lộc,\nGia môn hòa thuận, sao cát tường theo sau.",
    translation_en: "Fortune's time arrives, prosperity gradually rises,\nAll affairs bloom and flow smoothly bit by bit.\nAuspicious energy from the east brings added blessings,\nFamily harmonious and joyful, lucky stars follow close behind.",
    meaning: "Vận khí đang trên đà phát triển đi lên mạnh mẽ, mọi khó khăn trước mắt đang dần lùi xa.",
    meaning_en: "Fortune is on a strong upward trajectory. All present difficulties are gradually receding.",
    details: {
      "Bản thân": "Khí chất hồi phục, vận may mỉm cười, làm việc gì cũng tự tin hơn.",
      "Gia trạch": "Gia đạo hưng vượng dần, không khí gia đình vui tươi hòa thuận.",
      "Mưu sự": "Công việc làm ăn bắt đầu có khởi sắc tốt đẹp, nên mở rộng từ từ.",
      "Cầu tài": "Tài lộc tăng tiến đều đặn, buôn bán sinh lời khá.",
      "Tật bệnh": "Bệnh tình thuyên giảm rõ rệt, sức khỏe chuyển biến tích cực.",
      "Hôn nhân": "Tình cảm mặn nồng tiến triển tốt đẹp, hứa hẹn tương lai tươi sáng.",
      "Xuất hành": "Xuất hành hướng Đông vô cùng cát lợi, dễ đón nhận tin mừng."
    },
    details_en: {
      "Personal": "Vitality recovers, luck smiles upon you, confidence grows in all endeavors.",
      "Home & Family": "Family gradually thriving, household atmosphere cheerful and harmonious.",
      "Plans & Career": "Business begins showing excellent improvement. Expand gradually.",
      "Wealth": "Finances steadily increasing, trade generates good profits.",
      "Health": "Illness significantly improving, health turning positive.",
      "Marriage": "Passionate feelings progressing beautifully, promising a bright future.",
      "Travel": "Traveling east is extremely auspicious, easy to receive good news."
    }
  },
  {
    id: 24,
    name: "Quẻ Số 24 - Thượng Thượng",
    name_en: "Stick #24 - Supreme Fortune",
    title: "Thiên Địa Giao Thái",
    title_en: "Heaven and Earth in Perfect Harmony",
    poem: "Thiên địa giao thái vạn vật sinh\nKhang trang đại lộ tự sinh thành\nKim ngân tài bảo vô hà hạn\nVận thế thông thiên thịnh thế danh.",
    poem_en: "Thiên địa giao thái vạn vật sinh\nKhang trang đại lộ tự sinh thành\nKim ngân tài bảo vô hà hạn\nVận thế thông thiên thịnh thế danh.",
    translation: "Trời đất giao hòa vạn vật sinh sôi,\nĐường lớn khang trang tự mở ra.\nVàng bạc của cải nhiều vô kể,\nVận thế ngút trời lập danh tiếng thời thịnh trị.",
    translation_en: "Heaven and earth unite in harmony, all things flourish,\nA grand boulevard opens naturally before you.\nGold, silver, and treasures beyond counting,\nFortune reaches the heavens, fame established in an era of prosperity.",
    meaning: "Thời kỳ thịnh vượng tột bậc, vạn vật sinh sôi nảy nở, tài lộc dồi dào sung túc.",
    meaning_en: "An era of supreme prosperity. All things flourish and multiply. Wealth and fortune abound in abundance.",
    details: {
      "Bản thân": "Vận khí vô cùng vững vàng mạnh mẽ, gặp nhiều may mắn hiếm thấy.",
      "Gia trạch": "Gia đạo đại cát thịnh vượng, mọi người bình an hạnh phúc đong đầy.",
      "Mưu sự": "Kế hoạch lớn thành công vang dội ngoài mong đợi, không gặp bất kỳ trở ngại nào.",
      "Cầu tài": "Tài lộc cực vượng, tiền bạc dồi dào đổ về như nước chảy.",
      "Tật bệnh": "Sức khỏe sung mãn vô biên, tinh thần sảng khoái vui tươi.",
      "Hôn nhân": "Lương duyên mỹ mãn tiền định, vợ chồng yêu thương tôn trọng nhau suốt đời.",
      "Xuất hành": "Xuất hành vô cùng thuận lợi hanh thông trăm bề."
    },
    details_en: {
      "Personal": "Fortune incredibly strong and stable, encountering rare good luck.",
      "Home & Family": "Supremely auspicious and prosperous household. Everyone safe and overflowing with happiness.",
      "Plans & Career": "Grand plans succeed resoundingly beyond expectations with zero obstacles.",
      "Wealth": "Wealth at its peak, money flowing in like a rushing river.",
      "Health": "Boundless vitality, spirits joyful and refreshed.",
      "Marriage": "A beautiful predestined match. Couple loves and respects each other for a lifetime.",
      "Travel": "Travel is supremely smooth and favorable in every way."
    }
  },
  {
    id: 25,
    name: "Quẻ Số 25 - Hạ Hạ",
    name_en: "Stick #25 - Misfortune",
    title: "Sơn Cùng Thủy Tận",
    title_en: "Mountains End and Waters Run Dry",
    poem: "Sơn cùng thủy tận nghi vô lộ\nMộ sắc mang mang bộ bộ nan\nTĩnh tâm thủ cựu cầu thiên mệnh\nMạc vọng hành động họa trung tàn.",
    poem_en: "Sơn cùng thủy tận nghi vô lộ\nMộ sắc mang mang bộ bộ nan\nTĩnh tâm thủ cựu cầu thiên mệnh\nMạc vọng hành động họa trung tàn.",
    translation: "Núi cùng nước kiệt ngỡ hết đường đi,\nBóng chiều mờ mịt bước chân gian nan.\nTĩnh tâm giữ cũ cầu mệnh trời ban,\nChớ hành động bừa bãi kẻo chuốc họa vào thân.",
    translation_en: "Mountains end and waters dry up — the path seems gone,\nDusk falls dimly, every step fraught with hardship.\nCalm the mind, hold steady, and pray for heaven's mercy,\nDo not act recklessly lest you invite disaster upon yourself.",
    meaning: "Rơi vào ngõ cụt bế tắc hoàn toàn. Đòi hỏi sự kiên nhẫn tĩnh lặng tuyệt đối, tránh mọi hành động nóng vội phá vỡ tình hình.",
    meaning_en: "Trapped in a complete dead end. Absolute quiet patience is required. Avoid any rash actions that would worsen the situation.",
    details: {
      "Bản thân": "Vận thế xuống thấp nhất đề phòng tiểu nhân hãm hại, tai nạn bất ngờ.",
      "Gia trạch": "Gia đạo lục đục bất hòa nghiêm trọng, tiền của suy kiệt.",
      "Mưu sự": "Kế hoạch gặp ngõ cụt thất bại hoàn toàn, nên dừng lại rút lui an toàn.",
      "Cầu tài": "Hao tài tốn của nặng nề đề phòng lừa gạt nợ nần chồng chất.",
      "Tật bệnh": "Bệnh tình diễn biến xấu nguy hiểm, cần kiên trì chữa trị khoa học.",
      "Hôn nhân": "Tình cảm rạn nứt khó cứu vãn, dễ xảy ra chia ly ly tán.",
      "Xuất hành": "Cấm kỵ đi xa, dễ gặp bất trắc nguy hiểm dọc đường đi."
    },
    details_en: {
      "Personal": "Fortune at its lowest. Guard against petty people causing harm and unexpected accidents.",
      "Home & Family": "Serious household discord and conflict. Finances depleted.",
      "Plans & Career": "Plans hit a dead end, complete failure. Stop and retreat safely.",
      "Wealth": "Heavy financial losses. Guard against fraud, debts piling up.",
      "Health": "Health deteriorating dangerously. Persistent medical treatment is essential.",
      "Marriage": "Relationship cracking beyond repair. Separation likely.",
      "Travel": "Absolutely forbidden to travel far. Dangerous incidents likely on the road."
    }
  },
  {
    id: 26,
    name: "Quẻ Số 26 - Trung Bình",
    name_en: "Stick #26 - Average Fortune",
    title: "Họa Phúc Tương Y",
    title_en: "Fortune and Misfortune Intertwined",
    poem: "Họa hề phúc sở ỷ, phúc hề họa sở phục\nThế sự vô thường tu tự thức\nTĩnh tâm vi thiện thiên ban phước\nTự hữu sinh quang độ hiểm nan.",
    poem_en: "Họa hề phúc sở ỷ, phúc hề họa sở phục\nThế sự vô thường tu tự thức\nTĩnh tâm vi thiện thiên ban phước\nTự hữu sinh quang độ hiểm nan.",
    translation: "Họa là nơi phúc dựa vào, phúc là nơi họa ẩn náu,\nViệc đời vô thường người nên tự biết lấy.\nTĩnh tâm làm việc thiện trời ban phước lành,\nTự có ánh sáng sinh cơ giúp vượt qua hiểm nguy.",
    translation_en: "Misfortune is where fortune leans, fortune is where misfortune hides,\nLife is impermanent — one should be self-aware.\nCalm the mind and do good — heaven bestows blessings,\nA light of hope will naturally help you overcome danger.",
    meaning: "Họa phúc khôn lường đan xen lẫn nhau. Cần khiêm tốn khi thành công và vững vàng khi gặp thất bại.",
    meaning_en: "Fortune and misfortune are unpredictable and intertwined. Be humble in success and steady in failure.",
    details: {
      "Bản thân": "Bản thân cần giữ tâm thái bình thản trước mọi thăng trầm cuộc sống.",
      "Gia trạch": "Gia đạo bình thường lúc vui lúc buồn đan xen cần bao dung thấu hiểu nhau.",
      "Mưu sự": "Thành công hay thất bại phụ thuộc vào sự tỉnh táo và biết dừng đúng lúc.",
      "Cầu tài": "Tài lộc có biến động lớn trồi sụt thất thường không nên tham lam lớn.",
      "Tật bệnh": "Sức khỏe bình thường đề phòng các bệnh cũ tái phát.",
      "Hôn nhân": "Tình cảm cần sự thấu hiểu từ hai phía tránh tranh cãi chuyện tiền bạc.",
      "Xuất hành": "Xuất hành vừa phải an toàn không nên đi quá xa lâu ngày."
    },
    details_en: {
      "Personal": "Maintain inner calm before all of life's ups and downs.",
      "Home & Family": "Household ordinary with alternating joy and sorrow. Tolerance and understanding are needed.",
      "Plans & Career": "Success or failure depends on staying alert and knowing when to stop.",
      "Wealth": "Finances fluctuate greatly and unpredictably. Avoid excessive greed.",
      "Health": "Average health. Guard against old ailments recurring.",
      "Marriage": "Relationship needs understanding from both sides. Avoid arguing about money.",
      "Travel": "Moderate travel is safe. Don't go too far or stay away too long."
    }
  },
  {
    id: 27,
    name: "Quẻ Số 27 - Thượng Cát",
    name_en: "Stick #27 - Great Fortune",
    title: "Ngũ Phúc Lâm Môn",
    title_en: "Five Blessings Arrive at the Door",
    poem: "Ngũ phúc lâm môn cát tinh chiếu\nGia đình hưng vượng vạn sự khang\nTài nguyên quảng tiến thiên thiên phú\nPhú quý vinh hoa lộc tự mang.",
    poem_en: "Ngũ phúc lâm môn cát tinh chiếu\nGia đình hưng vượng vạn sự khang\nTài nguyên quảng tiến thiên thiên phú\nPhú quý vinh hoa lộc tự mang.",
    translation: "Năm phước vào nhà sao lành chiếu rọi,\nGia đình hưng thịnh vạn sự bình an.\nNguồn tài lộc rộng mở ngày càng giàu có,\nPhú quý vinh hoa tài lộc tự mang đến.",
    translation_en: "Five blessings enter the home under lucky stars' illumination,\nFamily thrives with prosperity, all matters in good health.\nWealth's sources expand widely, growing richer day by day,\nPrestige, glory, and fortune naturally follow.",
    meaning: "Cát tinh cao chiếu, nhận được nhiều hồng ân trời ban, gia đình may mắn sung túc đủ đầy mọi mặt.",
    meaning_en: "Lucky stars shine brightly. Receiving heaven's abundant grace, family blessed with prosperity in all aspects.",
    details: {
      "Bản thân": "Vận khí hanh thông rực rỡ, cuộc sống vui vẻ hạnh phúc viên mãn.",
      "Gia trạch": "Gia môn thịnh vượng đầy ắp tiếng cười đón nhận nhiều hỷ sự.",
      "Mưu sự": "Công việc thuận lợi thăng quan tiến chức dễ dàng thuận lợi vô ngần.",
      "Cầu tài": "Tài lộc dồi dào kinh doanh buôn bán thu lợi lớn.",
      "Tật bệnh": "Khỏe mạnh cường tráng tinh thần phấn chấn lạc quan yêu đời.",
      "Hôn nhân": "Lương duyên hòa hợp gia đình hạnh phúc bền lâu.",
      "Xuất hành": "Xuất hành vô cùng thuận lợi gặt hái nhiều thắng lợi."
    },
    details_en: {
      "Personal": "Fortune brilliantly smooth, life joyful and perfectly fulfilled.",
      "Home & Family": "Household thriving with laughter, welcoming many celebrations.",
      "Plans & Career": "Work goes smoothly, promotions come easily and effortlessly.",
      "Wealth": "Abundant wealth, business and trade earning large profits.",
      "Health": "Strong and robust, spirits optimistic and life-loving.",
      "Marriage": "Harmonious good match, family happy and enduring.",
      "Travel": "Travel supremely favorable, reaping many victories."
    }
  },
  {
    id: 28,
    name: "Quẻ Số 28 - Hạ Cát",
    name_en: "Stick #28 - Below Average",
    title: "Kinh Cức Mãn Đồ",
    title_en: "A Path Covered with Thorns",
    poem: "Kinh cức mãn đồ bộ bộ nan\nDũng cảm tiến lên mạc thối nhàn\nLịch tận phong ba kiến thanh hải\nTự hữu quang minh chiếu ngọc quan.",
    poem_en: "Kinh cức mãn đồ bộ bộ nan\nDũng cảm tiến lên mạc thối nhàn\nLịch tận phong ba kiến thanh hải\nTự hữu quang minh chiếu ngọc quan.",
    translation: "Gai góc đầy đường đi mỗi bước đều khó khăn,\nDũng cảm tiến lên chớ lui bước lười nhác.\nTrải hết phong ba nhìn thấy biển xanh trong,\nTự có ánh sáng chiếu rọi cửa ngọc vinh quang.",
    translation_en: "Thorns cover the entire path — every step is difficult,\nBravely press forward, do not retreat into idleness.\nAfter enduring all storms, the clear blue sea appears,\nA bright light will naturally illuminate the jade gates of glory.",
    meaning: "Đường đi đầy chông gai chướng ngại vật cản lối. Chỉ có dũng cảm kiên cường chiến đấu mới mong đạt được vinh quang cuối con đường.",
    meaning_en: "The path is full of thorns and obstacles. Only brave and steadfast fighting can hope to achieve the glory at journey's end.",
    details: {
      "Bản thân": "Gặp nhiều áp lực thử thách lớn cần rèn luyện tinh thần sắt thép.",
      "Gia trạch": "Gia đạo có xáo trộn bất hòa cần bình tĩnh giải quyết tháo gỡ nút thắt.",
      "Mưu sự": "Gặp nhiều đối thủ cạnh tranh khốc liệt hoặc thủ tục khó khăn trở ngại.",
      "Cầu tài": "Tài lộc khó kiếm, kiếm tiền vất vả đòi hỏi nhiều nỗ lực phi thường.",
      "Tật bệnh": "Chú ý giữ gìn sức khỏe đề phòng kiệt sức do làm việc quá sức.",
      "Hôn nhân": "Tình cảm gặp nhiều ngăn cấm trắc trở thử thách lòng trung thủy.",
      "Xuất hành": "Hạn chế đi xa nếu đi phải chuẩn bị kế hoạch dự phòng chu đáo."
    },
    details_en: {
      "Personal": "Facing heavy pressure and great trials. Must forge an iron will.",
      "Home & Family": "Household disrupted with discord. Stay calm and untangle the knots.",
      "Plans & Career": "Fierce competition or bureaucratic obstacles to overcome.",
      "Wealth": "Wealth hard to earn. Making money requires extraordinary effort.",
      "Health": "Take care of health. Guard against exhaustion from overwork.",
      "Marriage": "Relationship faces many prohibitions and obstacles testing fidelity.",
      "Travel": "Limit long trips. If traveling, prepare thorough backup plans."
    }
  },
  {
    id: 29,
    name: "Quẻ Số 29 - Trung Cát",
    name_en: "Stick #29 - Good Fortune",
    title: "Xuân Phong Hóa Vũ",
    title_en: "Spring Breeze Turns to Gentle Rain",
    poem: "Xuân phong hóa vũ nhuận quần sinh\nVạn sự thông đạt tự hữu tình\nKỷ vãng khai lai đa cát lợi\nGia môn hỷ khí tiếu đàm thanh.",
    poem_en: "Xuân phong hóa vũ nhuận quần sinh\nVạn sự thông đạt tự hữu tình\nKỷ vãng khai lai đa cát lợi\nGia môn hỷ khí tiếu đàm thanh.",
    translation: "Gió xuân mưa móc thấm nhuần muôn loài,\nMọi việc thông suốt tự nhiên có tình nghĩa.\nKế thừa quá khứ mở ra tương lai nhiều cát lợi,\nGia môn vui tươi rộn rã tiếng cười nói chuyện.",
    translation_en: "Spring breeze and nurturing rain nourish all living things,\nAll affairs flow smoothly with natural grace and sentiment.\nBuilding on the past to open a future of great fortune,\nThe household is lively with joyful laughter and conversation.",
    meaning: "Công danh sự nghiệp và cuộc sống gia đình được hưởng lợi nhờ lòng nhân ái bao dung và ứng xử thấu tình đạt lý.",
    meaning_en: "Career and family life benefit from kindness, compassion, and wise conduct that is both empathetic and rational.",
    details: {
      "Bản thân": "Bản thân có uy tín và lòng tốt được mọi người tôn trọng kính nể.",
      "Gia trạch": "Gia đình đầm ấm hòa thuận đầy ắp tình yêu thương sẻ chia.",
      "Mưu sự": "Thuận lợi nhờ tinh thần hợp tác đôi bên cùng có lợi.",
      "Cầu tài": "Tài lộc khá tốt tiền bạc đến từ sự chân thành và uy tín trong làm ăn.",
      "Tật bệnh": "Sức khỏe dồi dào bệnh nhẹ tiêu tan nhanh chóng.",
      "Hôn nhân": "Nhân duyên hòa hợp tốt lành gia đình hạnh phúc ấm êm.",
      "Xuất hành": "Xuất hành du lịch cầu tài lộc cầu bình an vô cùng thuận lợi."
    },
    details_en: {
      "Personal": "You carry prestige and kindness, earning everyone's respect and admiration.",
      "Home & Family": "Warm and harmonious household overflowing with love and sharing.",
      "Plans & Career": "Favorable thanks to a spirit of mutually beneficial cooperation.",
      "Wealth": "Good wealth from sincerity and trustworthy business dealings.",
      "Health": "Abundant health, minor illness quickly vanishes.",
      "Marriage": "Harmonious and good match. Family happy and warm.",
      "Travel": "Travel for fortune or for blessings is supremely favorable."
    }
  },
  {
    id: 30,
    name: "Quẻ Số 30 - Thượng Thượng",
    name_en: "Stick #30 - Supreme Fortune",
    title: "Càn Khôn Định Vị",
    title_en: "Heaven and Earth Firmly Established",
    poem: "Càn khôn đại định vạn sự hưng\nVạn cổ thiên thu lộc tự sinh\nThế sự hanh thông quang thế đại\nKim triều vinh hiển hiển gia minh.",
    poem_en: "Càn khôn đại định vạn sự hưng\nVạn cổ thiên thu lộc tự sinh\nThế sự hanh thông quang thế đại\nKim triều vinh hiển hiển gia minh.",
    translation: "Trời đất đại định vạn sự hưng thịnh,\nMuôn đời ngàn năm tài lộc tự sinh ra.\nViệc đời hanh thông làm sáng tỏ thế hệ,\nHôm nay vinh hiển làm rạng rỡ gia tộc danh tiếng.",
    translation_en: "Heaven and earth firmly established — all things prosper,\nThrough ten thousand ages, fortune naturally arises.\nWorldly affairs flow smoothly, illuminating the generation,\nToday's glory brings radiance to the family name.",
    meaning: "Sự nghiệp công danh vững chắc kiên cố như bàn thạch, tài lộc muôn đời vinh hoa hiển đạt vẻ vang gia môn.",
    meaning_en: "Career and prestige are as solid and unshakable as a mountain. Fortune for all ages, glory and honor illuminating the family legacy.",
    details: {
      "Bản thân": "Bản mệnh đại cát vững vàng tài giỏi đạt thành tựu tột đỉnh vinh quang.",
      "Gia trạch": "Gia đạo vô cùng hưng vượng giàu sang phú quý ngập tràn niềm vui gia tộc.",
      "Mưu sự": "Kế hoạch lớn lao kiên cố thành công mỹ mãn đặt nền móng lâu dài.",
      "Cầu tài": "Tài lộc thịnh vượng tích lũy được nhiều tài sản của cải giá trị lớn.",
      "Tật bệnh": "Khỏe mạnh trường thọ tinh thần sung mãn vô ưu vô lo.",
      "Hôn nhân": "Hôn nhân hạnh phúc viên mãn trăm năm bạc đầu nghĩa tình sâu đậm.",
      "Xuất hành": "Xuất hành vô cùng đại cát đi đâu cũng gặt hái thành công danh vọng vẻ vang."
    },
    details_en: {
      "Personal": "Supremely auspicious destiny, talented and achieving the pinnacle of glory.",
      "Home & Family": "Supremely prosperous household, wealth and joy overflowing throughout the clan.",
      "Plans & Career": "Grand plans succeed magnificently, laying a lasting foundation.",
      "Wealth": "Thriving wealth, accumulating assets of great value.",
      "Health": "Healthy and long-lived, spirits full without worry or concern.",
      "Marriage": "Marriage perfectly fulfilled, growing old together with deep love and devotion.",
      "Travel": "Supremely auspicious travel, harvesting success and glory wherever you go."
    }
  }
];
